[package]
name = "sudachi"
version = "0.1.0"
authors = ["Sorami Hisamoto <s@89.io>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
cfg-if = "0.1"
structopt = "0.2"
nom = "4.2.2"

[features]
# Compile dictionary into executable (specifying dictionary becomes optional)
bake_dictionary = []
