[workspace]
members = [
    "sudachi",
    "sudachi-cli",
    "plugin/connect_cost/*",
    "plugin/input_text/*",
    "plugin/oov/*",
    "plugin/path_rewrite/*",
]

default-members = [
    "sudachi",
    "sudachi-cli"
]